### ISSUE TITLE
As a player, I want to see the full map of Switzerland before zooming in to the correct location on the map.

### ISSUE THREAD

**Issue by laendi22** [sopra-fs24-group-46/client#33]
- [ ] sopra-fs24-group-46/server#68
- [ ] sopra-fs24-group-46/server#69
- [ ] sopra-fs24-group-46/server#70
